### ISSUE TITLE
Time is becoming multi-line

### ISSUE THREAD

**Issue by abhayjatindoshi** [TheAndroidMaster/Status#46] opened 2017-01-06 19:32 UTC
I tried to keep time, battery, network, wifi all right aligned and notification left aligned. The textview of time gets wrapped to second line. My current format is h:mm a but it displays as h:mm\n a on the statusbar

**Comment by TheAndroidMaster** [comment] 2017-01-06 19:35
This is a duplicate of #29. Please check the other issues before creating new ones.

**Closed by TheAndroidMaster** 2017-01-06 19:35 UTC
