### ISSUE TITLE
Icon layout

### ISSUE THREAD

**Issue by fangovk** [TheAndroidMaster/Status#95] opened 2017-07-02 05:40 UTC
I've notice when is more than 6-7 icons on the right side, last icons moves too much to the right, so it "hides" and I cant see them anymore .. even when i set horizontal padding to 0 on all icons .. the screen is not too small (5") and if I cut down icon(s) scale from the default soon all icons will be like on the stock status - too small.

**Comment by TheAndroidMaster** [comment] 2017-07-02 10:18
Duplicate of #29

**Closed** 2017-07-02 10:18 UTC
Labels: duplicate
