### ISSUE TITLE
Clock cutted

### ISSUE THREAD

**Issue by TheRedShadow** [TheAndroidMaster/Status#37] opened 2016-11-16 22:39 UTC
Zenfone 2, 6.0.1, non rooted, stock theme.

Hello,
When i apply the right alignment to the clock and 24 hours format the text goes down, I mean the time is divided in newlines.

Thanks for the help

**Comment by TheAndroidMaster** [comment] 2016-11-17 00:06
Duplicate of #29

**Closed by TheAndroidMaster** 2016-11-17 00:06 UTC
