### ISSUE TITLE
Clock text wraps to second line

### ISSUE THREAD

**Issue by LJB001** [TheAndroidMaster/Status#102] opened 2017-10-05 20:08 UTC
Frequently, the clock text at the far right side of STATUS wraps "AM/PM" to a second line of the status display.  If I stop & restart STATUS, the text "unwraps" to a single line display.  The format I am using is "h:mm a".  I have tried inserting a space prior to and after the format and also inserting two spaces prior to the "a" but the behavior is the same:  the text wraps to a second line.

Thanks for a GREAT app!!!

Status Version: 3.5 (problem also happened on the previous version)
Phone: Samsung Galaxy Luna
Android Version 6.0.1

**Comment by TheAndroidMaster** [comment] 2017-10-05 22:15
Thank you for your support and excellent bug reporting, including the app version and android version which almost nobody ever actually includes :+1: 

Unfortunately, this is a duplicate of #29, which has actually existed since the very first version of the app, and I haven't yet been able to find a satisfactory solution. But thanks anyway for the helpful reminder that it exists :neutral_face:

**Closed by TheAndroidMaster** 2017-10-05 22:15 UTC
Labels: duplicate
